import {
  Appliance,
  RoomUsage,
  ConsumptionDataPoint,
  PredictionDataPoint,
  AlertItem,
  RecommendationItem,
  HardwareNode,
  HardwareBOMItem,
  SystemHealth,
  TariffSettings,
} from '../types';

export const initialTariff: TariffSettings = {
  rate_per_kwh: 6.0,
  currency_symbol: '₹',
  peak_hours_start: '18:00',
  peak_hours_end: '22:00',
  peak_multiplier: 1.25,
  eco_mode_active: true,
  refresh_interval_sec: 2,
  budget_monthly_kwh: 180,
};

export const initialAppliances: Appliance[] = [
  {
    id: 'app-fan',
    name: 'Ceiling Fan',
    room: 'Living Room',
    type: 'fan',
    status: 'online',
    current_power: 72,
    voltage: 231.2,
    current: 0.31,
    energy_today: 1.84,
    estimated_cost: 11.04,
    is_abnormal: true,
    abnormality_note: 'Consumption is 42% above normal evening baseline',
    relay_state: true,
    eco_rating: 4,
    daily_limit_kwh: 2.0,
    carbon_footprint_kg: 1.47,
    icon_name: 'Fan',
  },
  {
    id: 'app-lamp',
    name: 'Smart Ambient Lamp',
    room: 'Bedroom',
    type: 'lamp',
    status: 'online',
    current_power: 24,
    voltage: 230.8,
    current: 0.10,
    energy_today: 1.21,
    estimated_cost: 7.26,
    is_abnormal: false,
    relay_state: true,
    eco_rating: 5,
    daily_limit_kwh: 1.5,
    carbon_footprint_kg: 0.97,
    icon_name: 'Lightbulb',
  },
  {
    id: 'app-laptop',
    name: 'Workstation Laptop',
    room: 'Bedroom',
    type: 'laptop',
    status: 'online',
    current_power: 65,
    voltage: 229.5,
    current: 0.28,
    energy_today: 0.97,
    estimated_cost: 5.82,
    is_abnormal: false,
    relay_state: true,
    eco_rating: 4,
    daily_limit_kwh: 1.8,
    carbon_footprint_kg: 0.78,
    icon_name: 'Laptop',
  },
  {
    id: 'app-refrig',
    name: 'Eco Inverter Fridge',
    room: 'Kitchen',
    type: 'refrigerator',
    status: 'online',
    current_power: 115,
    voltage: 231.0,
    current: 0.50,
    energy_today: 0.80,
    estimated_cost: 4.80,
    is_abnormal: false,
    relay_state: true,
    eco_rating: 5,
    daily_limit_kwh: 1.2,
    carbon_footprint_kg: 0.64,
    icon_name: 'Refrigerator',
  },
];

export const initialRooms: RoomUsage[] = [
  {
    room: 'Bedroom',
    energy_kwh: 2.1,
    percentage: 44,
    appliance_count: 2,
    active_load_w: 89,
    carbon_kg: 1.68,
    color: '#10B981', // Emerald
  },
  {
    room: 'Living Room',
    energy_kwh: 1.5,
    percentage: 31,
    appliance_count: 1,
    active_load_w: 72,
    carbon_kg: 1.20,
    color: '#059669', // Dark Emerald
  },
  {
    room: 'Kitchen',
    energy_kwh: 0.9,
    percentage: 19,
    appliance_count: 1,
    active_load_w: 115,
    carbon_kg: 0.72,
    color: '#14B8A6', // Teal
  },
  {
    room: 'Others',
    energy_kwh: 0.4,
    percentage: 6,
    appliance_count: 1,
    active_load_w: 18,
    carbon_kg: 0.32,
    color: '#84CC16', // Lime
  },
];

export const dayConsumptionData: ConsumptionDataPoint[] = [
  { timeLabel: '00:00', actual: 0.12, previous: 0.15, peak: 0.35, average: 0.20 },
  { timeLabel: '02:00', actual: 0.08, previous: 0.11, peak: 0.35, average: 0.20 },
  { timeLabel: '04:00', actual: 0.06, previous: 0.09, peak: 0.35, average: 0.20 },
  { timeLabel: '06:00', actual: 0.18, previous: 0.22, peak: 0.35, average: 0.20 },
  { timeLabel: '08:00', actual: 0.32, previous: 0.38, peak: 0.35, average: 0.20 },
  { timeLabel: '10:00', actual: 0.24, previous: 0.27, peak: 0.35, average: 0.20 },
  { timeLabel: '12:00', actual: 0.28, previous: 0.31, peak: 0.35, average: 0.20 },
  { timeLabel: '14:00', actual: 0.22, previous: 0.29, peak: 0.35, average: 0.20 },
  { timeLabel: '16:00', actual: 0.30, previous: 0.34, peak: 0.35, average: 0.20 },
  { timeLabel: '18:00', actual: 0.46, previous: 0.41, peak: 0.48, average: 0.20, isPeakHour: true },
  { timeLabel: '20:00', actual: 0.52, previous: 0.44, peak: 0.48, average: 0.20, isPeakHour: true },
  { timeLabel: '22:00', actual: 0.36, previous: 0.38, peak: 0.48, average: 0.20, isPeakHour: true },
];

export const weekConsumptionData: ConsumptionDataPoint[] = [
  { timeLabel: 'Mon', actual: 4.65, previous: 5.12, peak: 5.4, average: 4.8 },
  { timeLabel: 'Tue', actual: 4.90, previous: 5.30, peak: 5.4, average: 4.8 },
  { timeLabel: 'Wed', actual: 5.05, previous: 5.42, peak: 5.4, average: 4.8 },
  { timeLabel: 'Thu', actual: 4.70, previous: 5.10, peak: 5.4, average: 4.8 },
  { timeLabel: 'Fri', actual: 5.30, previous: 5.80, peak: 5.4, average: 4.8 },
  { timeLabel: 'Sat', actual: 5.85, previous: 6.20, peak: 5.4, average: 4.8 },
  { timeLabel: 'Sun (Today)', actual: 4.82, previous: 5.48, peak: 5.4, average: 4.8 },
];

export const monthConsumptionData: ConsumptionDataPoint[] = [
  { timeLabel: 'Week 1', actual: 34.2, previous: 38.5, peak: 42.0, average: 36.0 },
  { timeLabel: 'Week 2', actual: 32.8, previous: 37.1, peak: 42.0, average: 36.0 },
  { timeLabel: 'Week 3', actual: 35.1, previous: 39.0, peak: 42.0, average: 36.0 },
  { timeLabel: 'Week 4 (Current)', actual: 29.4, previous: 36.8, peak: 42.0, average: 36.0 },
];

export const forecastData: PredictionDataPoint[] = [
  { date: '2026-09-16', label: 'Sep 16', actual: 5.12, predicted: 5.08, confidence: 96, lowerBound: 4.8, upperBound: 5.4, isForecast: false },
  { date: '2026-09-17', label: 'Sep 17', actual: 4.95, predicted: 4.98, confidence: 95, lowerBound: 4.7, upperBound: 5.3, isForecast: false },
  { date: '2026-09-18', label: 'Sep 18 (Today)', actual: 4.82, predicted: 4.85, confidence: 97, lowerBound: 4.6, upperBound: 5.1, isForecast: false },
  { date: '2026-09-19', label: 'Sep 19 (Tomorrow)', predicted: 5.10, confidence: 94, lowerBound: 4.8, upperBound: 5.4, isForecast: true },
  { date: '2026-09-20', label: 'Sep 20', predicted: 5.25, confidence: 91, lowerBound: 4.9, upperBound: 5.6, isForecast: true },
  { date: '2026-09-21', label: 'Sep 21', predicted: 4.90, confidence: 89, lowerBound: 4.5, upperBound: 5.3, isForecast: true },
  { date: '2026-09-22', label: 'Sep 22', predicted: 4.75, confidence: 88, lowerBound: 4.3, upperBound: 5.2, isForecast: true },
];

export const initialAlerts: AlertItem[] = [
  {
    id: 'alert-01',
    severity: 'warning',
    device: 'Ceiling Fan',
    room: 'Living Room',
    timestamp: 'Today, 19:42',
    message: 'High usage detected: 2.8 kWh in 2 hours',
    expected_value: '1.97 kWh',
    actual_value: '2.80 kWh',
    difference: '+42% above normal',
    ai_explanation: 'Consumption is 42% above the normal evening pattern. Potential bearing mechanical drag, voltage sag, or prolonged max-speed operation while room is empty.',
    recommended_action: 'Inspect fan regulator, toggle Eco-Speed mode, or execute remote relay switch-off.',
    status: 'active',
  },
  {
    id: 'alert-02',
    severity: 'info',
    device: 'Smart Ambient Lamp',
    room: 'Bedroom',
    timestamp: 'Today, 14:15',
    message: 'Daylight waste warning',
    expected_value: '0 W (Daylight)',
    actual_value: '24 W',
    difference: 'Unnecessary Daylight Load',
    ai_explanation: 'Ambient luminance in bedroom is sufficient (>450 lux), but lighting circuit remained energized for 1.8 hrs.',
    recommended_action: 'Turn off ambient lamp during sunlight hours or enable photo-sensor auto-cutoff.',
    status: 'active',
  },
  {
    id: 'alert-03',
    severity: 'resolved',
    device: 'Workstation Laptop',
    room: 'Bedroom',
    timestamp: 'Yesterday, 23:10',
    message: 'Standby phantom load eliminated',
    expected_value: '< 5 W',
    actual_value: '18 W',
    difference: 'Mitigated',
    ai_explanation: 'Charger brick was drawing continuous vampire power while battery was at 100%. Auto-relay cut load safely.',
    recommended_action: 'Resolved by EcoMind automated cutoff rule.',
    status: 'resolved',
  },
];

export const initialRecommendations: RecommendationItem[] = [
  {
    id: 'rec-01',
    title: 'Reduce Evening Fan Consumption',
    category: 'peak_hours',
    reason: 'The fan is consuming approximately 18% more energy than its historical evening baseline between 6 PM and 10 PM peak tariff hours.',
    estimated_energy_saving: '0.38 kWh/day',
    estimated_cost_saving: '₹68/month',
    carbon_saving_kg: 9.12,
    confidence: 94,
    status: 'pending',
    impact_level: 'High',
    action_label: 'Apply Suggestion',
  },
  {
    id: 'rec-02',
    title: 'Eliminate Workstation Standby Loads',
    category: 'standby',
    reason: 'Laptop docking brick draws 8-14W idle after 11 PM. You could save approximately ₹150/month by scheduling automatic night standby disconnection.',
    estimated_energy_saving: '0.85 kWh/day',
    estimated_cost_saving: '₹153/month',
    carbon_saving_kg: 20.4,
    confidence: 91,
    status: 'pending',
    impact_level: 'High',
    action_label: 'Enable Night Sleep Schedule',
  },
  {
    id: 'rec-03',
    title: 'Optimize Peak-Hour Tariff Shifting',
    category: 'efficiency',
    reason: 'Shift high-consumption cyclical loads (e.g. heating or refrigeration defrost cycles) outside the 6 PM - 10 PM slot to take advantage of off-peak solar/green rates.',
    estimated_energy_saving: '0.52 kWh/day',
    estimated_cost_saving: '₹94/month',
    carbon_saving_kg: 12.48,
    confidence: 88,
    status: 'pending',
    impact_level: 'Medium',
    action_label: 'Activate Eco-Scheduler',
  },
];

export const hardwareNodes: HardwareNode[] = [
  {
    id: 'node-appliance',
    name: 'AC / Monitored Appliance',
    subtitle: 'Electrical Load Under Test',
    category: 'sensor',
    description: 'Domestic AC appliances (Fans, Lamps, PCs, Refrigeration) operating at 230V AC / 50Hz single-phase mains electricity.',
    specs: {
      'Operating Voltage': '220V - 240V AC',
      'Mains Frequency': '50 Hz ± 0.5 Hz',
      'Rated Current': '0.1A - 10A continuous',
      'Safety Standard': 'IEC 60335 compliant',
    },
    status: 'active',
    status_label: 'Connected Load',
  },
  {
    id: 'node-sensors',
    name: 'Voltage & Current Sensors',
    subtitle: 'ZMPT101B + ACS712-20A',
    category: 'sensor',
    description: 'Precision analog transducers measuring instantaneous potential difference (V) and alternating current (I) at a 1 kHz sampling frequency for true RMS & power factor calculation.',
    specs: {
      'Voltage Sensor': 'ZMPT101B High-Precision Micro AC Voltage Transformer',
      'Current Sensor': 'Allegro ACS712 Hall-Effect Isolated 20A Sensor',
      'Sampling Rate': '1,000 samples/sec (True RMS)',
      'Signal Conditioning': 'Active OP-AMP offset filter (0-3.3V ADC range)',
    },
    pinout: 'ZMPT101B OUT -> ESP32 GPIO34 (ADC1_CH6) | ACS712 OUT -> ESP32 GPIO35 (ADC1_CH7)',
    status: 'active',
    status_label: 'Sampling 1 kHz',
  },
  {
    id: 'node-esp32',
    name: 'ESP32 Microcontroller',
    subtitle: 'Dual-Core IoT Brain (240MHz)',
    category: 'controller',
    description: 'Xtensa 32-bit LX6 dual-core microcontroller responsible for ADC digital sampling, offset calibration, power factor calculation, MQTT/HTTP packet construction, and local fail-safe relay switching.',
    specs: {
      'MCU Architecture': 'Xtensa Dual-Core 32-bit LX6 @ 240 MHz',
      'Flash Memory': '4MB SPI Flash',
      'ADC Resolution': '12-bit SAR ADC (4096 levels)',
      'Wireless Connectivity': 'Wi-Fi 802.11 b/g/n + Bluetooth v4.2 BR/EDR',
      'Firmware Protocol': 'FreeRTOS with asynchronous task scheduling',
    },
    pinout: 'GPIO34: Volt ADC | GPIO35: Curr ADC | GPIO26: Relay Control | 3V3 / GND Power Rail',
    status: 'active',
    status_label: 'Operational / FreeRTOS',
  },
  {
    id: 'node-wifi',
    name: 'Wi-Fi 802.11 b/g/n',
    subtitle: 'Wireless Local Network Uplink',
    category: 'network',
    description: 'High-speed 2.4 GHz wireless communication uplink transmitting encrypted JSON telemetry packets to local gateway with auto-reconnect and offline buffering in EEPROM.',
    specs: {
      'Frequency Band': '2.4 GHz ISM Band',
      'Security': 'WPA2-PSK Enterprise',
      'Signal Strength (RSSI)': '-58 dBm (Strong)',
      'Telemetry Interval': '2000 ms (Configurable)',
    },
    status: 'active',
    status_label: 'RSSI -58 dBm',
  },
  {
    id: 'node-backend',
    name: 'Backend API Gateway',
    subtitle: 'REST & MQTT Ingestion Server',
    category: 'backend',
    description: 'High-throughput ingestion layer validating sensor cryptographic signatures, parsing device payloads, and dispatching to time-series persistent storage.',
    specs: {
      'Architecture': 'FastAPI / Node.js Express Gateway',
      'Protocol': 'HTTP/2 REST API + MQTT Broker (Mosquitto)',
      'Throughput': '1,200 requests/sec peak',
      'Data Integrity': 'SHA-256 HMAC payload verification',
    },
    status: 'active',
    status_label: 'HTTP 200 OK',
  },
  {
    id: 'node-database',
    name: 'Time-Series Database',
    subtitle: 'PostgreSQL / TimescaleDB Engine',
    category: 'backend',
    description: 'Hypertable optimized for sub-second electrical metrics, continuous rollups (minute/hour/day aggregates), and high-cardinality appliance telemetry partitioning.',
    specs: {
      'Database Engine': 'TimescaleDB (PostgreSQL 16)',
      'Storage Model': 'Compressed Hypertables with 7-day retention chunking',
      'Query Latency': '< 4ms p95 aggregate retrieval',
      'Persistence': 'ACID compliant with automated write-ahead logging',
    },
    status: 'active',
    status_label: 'Hypertables Active',
  },
  {
    id: 'node-ai',
    name: 'AI / ML Intelligence Engine',
    subtitle: 'Scikit-Learn & ARIMA Forecast Model',
    category: 'ai',
    description: 'Autonomous machine learning pipeline running isolation forest anomaly detection, dynamic rolling baseline regression, and day-ahead ARIMA/LSTM consumption forecasting.',
    specs: {
      'Anomaly Model': 'Isolation Forest & Z-Score Deviation (3.2σ threshold)',
      'Forecasting Model': 'SARIMAX + XGBoost Hybrid Energy Forecaster',
      'Inference Speed': '18 ms per batch evaluation',
      'Recommendation Agent': 'Energy Optimization Rule Engine + Gemini LLM Insights',
    },
    status: 'active',
    status_label: 'Model Confidence 94%',
  },
  {
    id: 'node-dashboard',
    name: 'EcoMind Web Dashboard',
    subtitle: 'Live Telemetry & User Interface',
    category: 'dashboard',
    description: 'Modern, sustainability-first light theme responsive user interface providing real-time watt telemetry, room breakdowns, cost forecasting, and alert management.',
    specs: {
      'Frontend Framework': 'React 19 + TypeScript + Tailwind CSS',
      'State Sync': 'Real-time WebSocket & REST polling (2s)',
      'UI Architecture': 'Modular component hierarchy with Recharts visualizer',
      'Accessibility': 'WCAG AA high-contrast design with eco palette',
    },
    status: 'active',
    status_label: 'Rendering Live',
  },
  {
    id: 'node-relay',
    name: 'Remote Relay Actuator',
    subtitle: 'Isolated 5V SPDT Load Control',
    category: 'actuator',
    description: 'Optocoupler-isolated 10A 250V AC relay module allowing automated software cutoff on critical alerts or manual user-controlled remote load shedding.',
    specs: {
      'Relay Type': '5V Single-Channel SPDT Mechanical Relay',
      'Isolation': 'Optocoupler PC817 Galvanic Isolation',
      'Contact Rating': '10A 250V AC / 10A 30V DC',
      'Control Logic': 'Active-LOW driven by ESP32 GPIO26 transistor stage',
    },
    pinout: 'IN -> ESP32 GPIO26 | VCC -> 5V DC | GND -> System GND | COM/NO -> AC Live Line',
    status: 'active',
    status_label: 'Relay Ready (GPIO26)',
  },
];

export const hardwareBOM: HardwareBOMItem[] = [
  {
    component: 'ESP32 Development Board',
    model: 'NodeMCU ESP-WROOM-32 (30-Pin)',
    quantity: 1,
    role: 'Central IoT processor, ADC conversion, Wi-Fi telemetry',
    pinConnection: 'GPIO34, GPIO35, GPIO26, 3.3V, GND',
    voltageRating: '3.3V logic (5V MicroUSB Input)',
    status: 'operational',
  },
  {
    component: 'AC Voltage Sensor Module',
    model: 'ZMPT101B Active Transformer Module',
    quantity: 1,
    role: 'Mains potential measurement with adjustable op-amp gain',
    pinConnection: 'VCC (5V), GND, OUT -> GPIO34',
    voltageRating: 'Up to 250V AC input, 0-3.3V analog out',
    status: 'operational',
  },
  {
    component: 'AC Current Sensor Module',
    model: 'Allegro ACS712ELCTR-20A-T',
    quantity: 1,
    role: 'Hall-effect isolated in-line alternating current measurement',
    pinConnection: 'VCC (5V), GND, OUT -> GPIO35',
    voltageRating: '±20A range (100 mV/A sensitivity)',
    status: 'operational',
  },
  {
    component: 'Optocoupled Relay Module',
    model: 'Songle SRD-05VDC-SL-C (1-Channel)',
    quantity: 1,
    role: 'Remote load control and emergency automated trip cutoff',
    pinConnection: 'VCC (5V), GND, IN -> GPIO26',
    voltageRating: '10A @ 250V AC contact rating',
    status: 'operational',
  },
  {
    component: 'Regulated DC Power Supply',
    model: 'Hi-Link HLK-PM01 / 5V 2A Adapter',
    quantity: 1,
    role: 'Step-down isolated DC power for ESP32 and sensor modules',
    pinConnection: '230V AC in -> 5.0V DC regulated out',
    voltageRating: '5V DC @ 2000mA',
    status: 'operational',
  },
  {
    component: 'Prototyping Board & Wiring',
    model: 'FR4 PCB / High-grade Solderless Breadboard',
    quantity: 1,
    role: 'High-voltage creepage separation, 18 AWG AC lines, signal shielding',
    pinConnection: 'Standard 2.54mm pitch + Screw terminals for AC',
    voltageRating: 'Insulated up to 600V peak',
    status: 'operational',
  },
];

export const initialSystemHealth: SystemHealth = {
  esp32_status: 'CONNECTED',
  wifi_status: 'CONNECTED',
  api_status: 'OPERATIONAL',
  database_status: 'OPERATIONAL',
  ai_engine_status: 'READY',
  last_sensor_update: '2 seconds ago',
  rssi: -58,
  ping_ms: 14,
  packet_loss_pct: 0.0,
  voltage_grid: 231.4,
  frequency: 50.02,
  eco_score: 92,
};
