import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, BarChart3, Bell, BrainCircuit, Check, ChevronRight, CircleHelp, Cpu, Gauge, LayoutDashboard, Leaf, Lightbulb, Menu, MonitorCog, Moon, Network, PanelLeftClose, PanelLeftOpen, Power, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Sun, Thermometer, TrendingDown, TrendingUp, Wifi, X, Zap } from 'lucide-react';
import { dayConsumptionData, forecastData, initialAppliances, initialRooms } from '../services/mockData';

type Page = 'dashboard' | 'live' | 'analytics' | 'ai' | 'hardware' | 'settings';
const nav = [
  ['dashboard', 'Dashboard', LayoutDashboard], ['live', 'Live Monitoring', Activity], ['analytics', 'Analytics', BarChart3], ['ai', 'AI Intelligence', BrainCircuit], ['hardware', 'Hardware', Cpu], ['settings', 'Settings', Settings],
] as const;
const liveSeries = Array.from({ length: 18 }, (_, i) => ({ time: `${i + 1}:0${i % 6}`, voltage: 229 + (i % 5) * 0.7, current: 0.27 + (i % 4) * 0.02, power: 66 + (i % 6) * 2 }));
const hardware = [
  ['Appliance', 'Source load', 'The monitored appliance provides the electrical load.'], ['Voltage Sensor', 'Measures voltage', 'Captures the appliance voltage used for power and energy calculations.'], ['Current Sensor', 'Measures current', 'Measures the current drawn by the connected appliance.'], ['ESP32', 'Controller', 'Wi-Fi-enabled microcontroller collecting readings and transmitting them to the backend.'], ['Wi-Fi', 'Transport', 'Carries sensor measurements securely from the ESP32 to the API.'], ['Backend API', 'Data service', 'Normalizes readings and prepares them for analytics and AI analysis.'], ['AI / ML Engine', 'Intelligence', 'Produces forecasts, anomaly detection, and energy-saving recommendations.'], ['EcoMind Dashboard', 'Control center', 'Turns device telemetry into clear, actionable decisions.'], ['Relay Module', 'Optional actuator', 'Provides remote switching for a connected load when the device is online.'],
];

function Badge({ children, tone = 'demo' }: { children: React.ReactNode; tone?: 'live' | 'demo' | 'predicted' | 'warning' }) { return <span className={`badge badge-${tone}`}><i />{children}</span> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }
function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="section-title"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div> }

export default function EcoMindPrototype() {
  const [page, setPage] = useState<Page>('dashboard');
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [dark, setDark] = useState(false);
  const [relay, setRelay] = useState(true);
  const [confirmRelay, setConfirmRelay] = useState(false);
  const [notice, setNotice] = useState('');
  const [metric, setMetric] = useState<'voltage' | 'current' | 'power'>('power');
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; }, [dark]);
  useEffect(() => { if (!notice) return; const t = setTimeout(() => setNotice(''), 3200); return () => clearTimeout(t); }, [notice]);
  const navigate = (next: Page) => { setPage(next); setMobileOpen(false); window.location.hash = next; window.scrollTo(0, 0); };
  const latest = { voltage: 231, current: 0.31, power: 72, energy: 1.84 };
  return <div className="app-shell">
    <aside className={`sidebar ${collapsed ? 'collapsed' : ''} ${mobileOpen ? 'mobile-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Leaf /></div><div><strong>Eco<span>Mind</span></strong><small>SMART ENERGY OS</small></div></div>
      <div className="sidebar-device"><div className="device-head"><span>DEVICE STATUS</span><Badge tone="live">ESP32 ONLINE</Badge></div><div className="device-reading"><Wifi /><div><strong>Connected</strong><small>Last update · 2 sec ago</small></div></div></div>
      <div className="sidebar-label">Workspace</div><nav>{nav.map(([id, label, Icon]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => navigate(id)}><Icon /><span>{label}</span>{id === 'live' && <em>LIVE</em>}{id === 'ai' && <em className="purple">AI</em>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="mode-card"><span><div className="pulse" />Demo environment</span><small>Simulated telemetry active</small></div><button className="collapse" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <PanelLeftOpen /> : <><PanelLeftClose /><span>Collapse menu</span></>}</button></div>
    </aside>
    {mobileOpen && <button className="mobile-scrim" onClick={() => setMobileOpen(false)} aria-label="Close menu" />}
    <main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu /></button><div className="crumb"><span>EcoMind</span><ChevronRight /><strong>{nav.find(n => n[0] === page)?.[1]}</strong></div><div className="top-actions"><span className="date">Monday, September 21, 2026</span><button className="icon-button"><Bell /><b>2</b></button><div className="avatar">AS</div></div></header>
      <div className="content">{page === 'dashboard' && <Dashboard latest={latest} navigate={navigate} relay={relay} setConfirmRelay={setConfirmRelay} />}{page === 'live' && <Live latest={latest} metric={metric} setMetric={setMetric} relay={relay} setConfirmRelay={setConfirmRelay} />}{page === 'analytics' && <Analytics />}{page === 'ai' && <AI />}{page === 'hardware' && <Hardware />}{page === 'settings' && <SettingsPage dark={dark} setDark={setDark} setNotice={setNotice} />}</div>
    </main>
    {confirmRelay && <div className="dialog-backdrop"><div className="dialog"><div className="dialog-icon"><Power /></div><h2>Change relay state?</h2><p>Are you sure you want to turn {relay ? 'OFF' : 'ON'} the Fan?</p><div className="dialog-actions"><button className="button ghost" onClick={() => setConfirmRelay(false)}>Cancel</button><button className="button primary" onClick={() => { setRelay(!relay); setConfirmRelay(false); setNotice(`Fan relay turned ${relay ? 'OFF' : 'ON'}.`); }}>{relay ? 'Turn OFF' : 'Turn ON'}</button></div></div></div>}
    {notice && <div className="toast"><Check />{notice}</div>}
  </div>
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Dashboard({ latest, navigate, relay, setConfirmRelay }: any) { return <><PageHeader eyebrow="MONDAY · 06:17 PM" title="Good evening, Alex" description="Here's how your energy usage looks today." action={<div className="header-status"><Badge tone="demo">DEMO DATA</Badge><div className="connection"><div className="pulse" /> ESP32 online</div></div>} />
  <div className="story-strip"><div className="story-icon"><Leaf /></div><div className="story-copy"><strong>Smarter Energy. Smarter Living.</strong><span>Measure · Monitor · Analyze · Predict · Optimize · Control</span></div><div className="overview-controls"><span className="overview-home"><span className="home-dot" />Alex&apos;s home</span><span className="overview-divider" /><span className="overview-range">Today <ChevronRight /></span></div><button onClick={() => navigate('hardware')}>View system flow <ChevronRight /></button></div>
  <div className="kpi-grid"><KPI icon={Gauge} label="Voltage" value="231" unit="V" meta="Stable grid input" /><KPI icon={Activity} label="Current" value="0.31" unit="A" meta="Sensor reading" /><KPI icon={Zap} label="Power" value="72" unit="W" meta="Instantaneous load" /><KPI icon={TrendingDown} label="Energy today" value="1.84" unit="kWh" meta="12% lower vs yesterday" positive /></div>
  <div className="dashboard-grid"><Card className="chart-card"><SectionTitle eyebrow="DEMO DATA · UPDATED 2 SEC AGO" title="Energy consumption" action={<div className="segmented"><button className="selected">Day</button><button>Week</button><button>Month</button></div>} /><div className="chart-legend"><span><i className="dot green" />Today</span><span><i className="dot gray" />Previous period</span><span><i className="line-dot" />Average 0.21 kWh</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dayConsumptionData}><defs><linearGradient id="energy" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7ee787" stopOpacity={.35}/><stop offset="1" stopColor="#7ee787" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--grid)"/><XAxis dataKey="timeLabel" tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(v) => `${v}`} /><Tooltip contentStyle={{ background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: 12 }} /><Area type="monotone" dataKey="previous" stroke="var(--muted)" strokeDasharray="5 5" fill="none" strokeWidth={1.5} /><Area type="monotone" dataKey="actual" stroke="#7ee787" fill="url(#energy)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span>Peak usage <strong>7–10 PM</strong></span><span>Today <strong>1.84 kWh</strong></span><span>Avg. <strong>0.21 kWh</strong></span></div></Card>
    <Card className="cost-card"><SectionTitle eyebrow="COST ESTIMATE" title="Today's cost" /><div className="cost-value">₹11.04</div><div className="cost-sub">at ₹6 / kWh tariff</div><div className="cost-divider" /><div className="cost-row"><span>Projected monthly</span><strong>₹342</strong></div><div className="cost-row"><span>vs last month</span><strong className="green-text">↓ 8.4%</strong></div><button className="text-button" onClick={() => navigate('settings')}>Configure tariff <ChevronRight /></button></Card></div>
  <div className="three-grid"><Card><SectionTitle eyebrow="WHERE ENERGY GOES" title="Appliances" action={<button className="small-link" onClick={() => navigate('analytics')}>Details <ChevronRight /></button>} /><Breakdown data={initialAppliances.map(a => ({ name: a.name, value: a.energy_today, color: ['#7ee787', '#6ec6ff', '#a78bfa', '#f6c85f'][initialAppliances.indexOf(a) % 4] }))} /></Card><Card><SectionTitle eyebrow="LOCATION BREAKDOWN" title="Rooms" /><Breakdown data={initialRooms.map(r => ({ name: r.room, value: r.energy_kwh, color: r.color }))} /></Card><Card className="forecast-card"><SectionTitle eyebrow="AI FORECAST · 87% CONFIDENCE" title="Consumption forecast" action={<Badge tone="predicted">PREDICTED</Badge>} /><div className="forecast-big">5.10 <small>kWh</small></div><p>Tomorrow's estimated consumption</p><div className="forecast-bar"><span style={{ width: '66%' }} /></div><div className="forecast-footer"><span>Today 4.82 kWh</span><strong>Tomorrow ↑ 5.10</strong></div><button className="text-button" onClick={() => navigate('ai')}>Explore forecast <ChevronRight /></button></Card></div>
  <div className="bottom-grid"><Card className="alert-card"><div className="alert-mark"><AlertTriangle /></div><div className="alert-content"><Badge tone="warning">ABNORMAL USAGE DETECTED</Badge><h3>Fan · Living Room</h3><p>Current consumption is <strong>42% above normal</strong> for this evening pattern.</p><span>“The fan is drawing more power than its historical baseline.”</span></div><button className="button ghost" onClick={() => navigate('ai')}>Investigate <ChevronRight /></button></Card><Card className="insight-card"><div className="ai-heading"><div className="ai-icon"><Sparkles /></div><div><div className="eyebrow">AI ENERGY INTELLIGENCE</div><h3>Your usage is 12% lower than yesterday.</h3></div></div><p>Reducing standby consumption could save approximately <strong>₹150/month</strong>.</p><div className="insight-foot"><span>Confidence <strong>91%</strong></span><button className="text-button" onClick={() => navigate('ai')}>See recommendations <ChevronRight /></button></div></Card></div>
  <RelayCard relay={relay} setConfirmRelay={setConfirmRelay} /></> }
function KPI({ icon: Icon, label, value, unit, meta, positive }: any) { return <Card className="kpi"><div className="kpi-top"><span>{label}</span><div className="kpi-icon"><Icon /></div></div><div className="kpi-value">{value}<small>{unit}</small></div><div className={positive ? 'kpi-meta positive' : 'kpi-meta'}><i />{meta}</div></Card> }
function Breakdown({ data }: any) { const total = data.reduce((a: number, b: any) => a + b.value, 0); return <div className="breakdown"><div className="donut"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" innerRadius={46} outerRadius={66} paddingAngle={3} strokeWidth={0}>{data.map((d: any) => <Cell key={d.name} fill={d.color} />)}</Pie></PieChart></ResponsiveContainer><div><strong>{total.toFixed(2)}</strong><small>kWh total</small></div></div><div className="breakdown-list">{data.map((d: any) => <div className="break-row" key={d.name}><span><i style={{ background: d.color }} />{d.name}</span><strong>{d.value.toFixed(2)} <small>kWh</small></strong></div>)}</div></div> }
function RelayCard({ relay, setConfirmRelay }: any) { return <Card className="relay-card"><div className="relay-info"><div className="relay-icon"><Power /></div><div><div className="eyebrow">DEMO RELAY CONTROL</div><h3>Living Room Fan</h3><p>ESP32 relay simulation · hardware command ready</p></div></div><div className="relay-status"><span className={relay ? 'status-on' : 'status-off'}><i />{relay ? 'ON' : 'OFF'}</span><button className="button primary" onClick={() => setConfirmRelay(true)}><Power />Turn {relay ? 'OFF' : 'ON'}</button></div></Card> }
function Live({ latest, metric, setMetric, relay, setConfirmRelay }: any) { const labels: any = { voltage: ['Voltage', '231', 'V'], current: ['Current', '0.31', 'A'], power: ['Power', '72', 'W'] }; return <><PageHeader eyebrow="REAL-TIME TELEMETRY" title="Live monitoring" description="Watch sensor readings as they move from the ESP32 to EcoMind." action={<Badge tone="live">LIVE SIMULATION</Badge>} /><div className="live-status"><div><div className="pulse" /><strong>ESP32 Connected</strong><span>Data stream active · updated every 2 sec</span></div><div className="live-tags"><Badge tone="live">LIVE</Badge><span>Wi-Fi · −42 dBm</span><span>API · Operational</span></div></div><div className="kpi-grid three"><KPI icon={Gauge} label="Voltage" value={latest.voltage} unit="V" meta="Stable" /><KPI icon={Activity} label="Current" value={latest.current} unit="A" meta="Sensor reading" /><KPI icon={Zap} label="Power" value={latest.power} unit="W" meta="Instantaneous load" /></div><Card className="chart-card live-chart"><SectionTitle eyebrow="LIVE TELEMETRY STREAM" title={`${labels[metric][0]} over time`} action={<div className="segmented">{(['voltage','current','power'] as const).map(m => <button key={m} className={metric === m ? 'selected' : ''} onClick={() => setMetric(m)}>{m}</button>)}</div>} /><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={liveSeries}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--grid)"/><XAxis dataKey="time" tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: 12 }}/><Area type="monotone" dataKey={metric} stroke="#6ec6ff" fill="#6ec6ff" fillOpacity={.16} strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></Card><div className="live-lower"><Card><SectionTitle eyebrow="DATA FLOW" title="From circuit to insight" /><Flow /></Card><RelayCard relay={relay} setConfirmRelay={setConfirmRelay} /></div></> }
function Flow() { return <div className="flow">{[['Voltage + current sensors', Gauge], ['ESP32', Cpu], ['Wi-Fi', Wifi], ['Backend API', Network], ['Dashboard', MonitorCog]].map(([label, Icon], i) => <div className="flow-node" key={label as string}><div><Icon /></div><span>{label as string}</span>{i < 4 && <b>→</b>}</div>)}</div> }
function Analytics() { return <><PageHeader eyebrow="ENERGY WORKSPACE" title="Analytics" description="Understand patterns across rooms, appliances, and time." action={<button className="button ghost"><SlidersHorizontal /> Filters</button>} /><div className="stat-row"><Stat label="Total energy" value="4.82 kWh" trend="↓ 12%" /><Stat label="Average daily" value="4.95 kWh" trend="↓ 8.4%" /><Stat label="Peak power" value="342 W" trend="7–10 PM" /><Stat label="Estimated bill" value="₹342" trend="this month" /></div><div className="dashboard-grid"><Card className="chart-card"><SectionTitle eyebrow="DAILY ENERGY · DEMO" title="Consumption trend" /><div className="chart tall"><ResponsiveContainer><BarChart data={dayConsumptionData}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--grid)"/><XAxis dataKey="timeLabel" tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: 12 }}/><Bar dataKey="actual" fill="#7ee787" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Card><Card><SectionTitle eyebrow="COST TREND" title="Monthly estimate" /><div className="analytics-total">₹342 <small>projected</small></div><div className="mini-bars">{[42, 57, 48, 69, 64, 78, 72, 84, 74, 91].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}</div><p className="muted">Tariff configured at ₹6 / kWh. Peak hours are included in the estimate.</p></Card></div><div className="three-grid"><Card><SectionTitle eyebrow="APPLIANCE" title="Consumption" /><Breakdown data={initialAppliances.map((a, i) => ({ name: a.name, value: a.energy_today, color: ['#7ee787','#6ec6ff','#a78bfa'][i % 3] }))} /></Card><Card><SectionTitle eyebrow="ROOM" title="Consumption" /><Breakdown data={initialRooms.map(r => ({ name: r.room, value: r.energy_kwh, color: r.color }))} /></Card><Card><SectionTitle eyebrow="PEAK USAGE" title="Time windows" /><div className="peak-item"><span>07:00 PM — 10:00 PM</span><strong>1.42 kWh</strong><div><i style={{ width: '82%' }} /></div></div><div className="peak-item"><span>09:00 AM — 12:00 PM</span><strong>0.86 kWh</strong><div><i style={{ width: '54%' }} /></div></div></Card></div></> }
function Stat({ label, value, trend }: any) { return <Card className="stat"><span>{label}</span><strong>{value}</strong><small>{trend}</small></Card> }
function AI() { const predictions = [['Next hour', '0.28 kWh', '93%'], ['Tomorrow', '5.10 kWh', '87%'], ['Next 7 days', '34.6 kWh', '81%']]; return <><PageHeader eyebrow="YOUR ENERGY DATA, UNDERSTOOD" title="AI Energy Intelligence" description="Forecasts, anomalies, and actions generated from your demo usage patterns." action={<Badge tone="predicted">PREDICTED DATA</Badge>} /><div className="ai-modules"><Card className="ai-module forecast-module"><div className="module-number">01</div><SectionTitle eyebrow="FORECASTING" title="What happens next?" /><div className="prediction-list">{predictions.map(p => <div className="prediction" key={p[0]}><div><span>{p[0]}</span><strong>{p[1]}</strong></div><Badge tone="predicted">{p[2]} confidence</Badge></div>)}</div><div className="prediction-chart"><ResponsiveContainer><AreaChart data={forecastData}><Area type="monotone" dataKey="actual" stroke="#7ee787" fill="none" strokeWidth={2}/><Area type="monotone" dataKey="predicted" stroke="#a78bfa" fill="#a78bfa" fillOpacity={.18} strokeWidth={2} strokeDasharray="6 4"/></AreaChart></ResponsiveContainer></div></Card><Card className="ai-module"><div className="module-number">02</div><SectionTitle eyebrow="ANOMALY DETECTION" title="Pattern deviation" /><div className="compare"><div><span>Normal pattern</span><strong>51 W</strong><small>historical baseline</small></div><div className="compare-arrow">→</div><div className="anomaly"><span>Detected pattern</span><strong>72 W</strong><small>+42% above baseline</small></div></div><div className="timeline"><i /><i /><i className="hot" /><i className="hot" /><i className="hot" /><i /><i /><i /><i /></div><p className="explain">Fan consumption is 42% higher than its historical evening baseline. This may indicate dust buildup or a mechanical issue.</p><button className="button ghost">Investigate anomaly <ChevronRight /></button></Card><Card className="ai-module recommendations"><div className="module-number">03</div><SectionTitle eyebrow="ENERGY-SAVING RECOMMENDATIONS" title="Actions that add up" /><Recommendation icon={Lightbulb} title="Reduce standby loads" reason="Standby consumption is active in the bedroom overnight." saving="₹150 / month" confidence="91%" /><Recommendation icon={TrendingDown} title="Shift peak usage" reason="Your peak consumption is concentrated between 7 PM and 10 PM." saving="0.8 kWh / day" confidence="84%" /><Recommendation icon={Thermometer} title="Inspect the fan" reason="Continuous running for 5.2 hours is above its normal pattern." saving="₹48 / month" confidence="88%" /></Card></div></> }
function Recommendation({ icon: Icon, title, reason, saving, confidence }: any) { return <div className="recommendation"><div className="rec-icon"><Icon /></div><div className="rec-body"><h3>{title}</h3><p>{reason}</p><div><span>Est. saving <strong>{saving}</strong></span><span>Confidence <strong>{confidence}</strong></span></div></div><button className="icon-button"><ChevronRight /></button></div> }
function Hardware() { const [selected, setSelected] = useState(3); return <><PageHeader eyebrow="PHYSICAL SYSTEM" title="Hardware architecture" description="See exactly how energy moves from the appliance to the intelligence layer." action={<Badge tone="demo">SIMULATED DEVICE STATUS</Badge>} /><Card className="architecture"><div className="architecture-flow">{hardware.map(([name, sub], i) => <button key={name} className={selected === i ? 'selected' : ''} onClick={() => setSelected(i)}><div className="arch-icon">{i === 0 ? <Power /> : i === 3 ? <Cpu /> : i === 4 ? <Wifi /> : i === 6 ? <BrainCircuit /> : i === 7 ? <MonitorCog /> : i === 8 ? <Zap /> : <Gauge />}</div><strong>{name}</strong><span>{sub}</span>{i < hardware.length - 1 && <ChevronRight />}</button>)}</div><div className="architecture-detail"><Badge tone="live">SELECTED COMPONENT</Badge><h2>{hardware[selected][0]}</h2><p>{hardware[selected][2]}</p><div className="detail-meta"><span>State <strong>{selected === 3 ? 'Connected' : 'Ready'}</strong></span><span>Mode <strong>Demo</strong></span></div></div></Card><div className="hardware-lower"><Card><SectionTitle eyebrow="CURRENT PROTOTYPE HARDWARE" title="Inventory" /><div className="inventory">{['ESP32', 'Voltage Sensor', 'Current Sensor', 'Relay Module', 'Fuse Holder', '2-Pin Terminal', 'Breadboard', 'Jumper Wires', 'Power Supply'].map(item => <div key={item}><Check />{item}<Badge tone="demo">READY</Badge></div>)}</div></Card><Card><SectionTitle eyebrow="SYSTEM STATUS" title="Services" /><div className="service-list">{[['ESP32', 'Connected'], ['Wi-Fi', 'Connected'], ['Backend', 'Operational'], ['AI Engine', 'Ready'], ['Last sensor update', '2 seconds ago']].map(s => <div key={s[0]}><span>{s[0]}</span><strong><i />{s[1]}</strong></div>)}</div></Card></div></> }
function SettingsPage({ dark, setDark, setNotice }: any) { return <><PageHeader eyebrow="PREFERENCES" title="Settings" description="Keep your EcoMind workspace tuned to the way you use energy." /><div className="settings-grid"><Card><SectionTitle eyebrow="ACCOUNT" title="Profile" /><div className="profile"><div className="avatar large">AS</div><div><strong>Alex Sharma</strong><span>alex@ecomind.demo</span></div><button className="button ghost">Sign out</button></div></Card><Card><SectionTitle eyebrow="ENERGY" title="Electricity tariff" /><div className="setting-row"><div><strong>Current tariff</strong><small>Used for cost estimates</small></div><div className="input-prefix"><span>₹</span><input defaultValue="6" onChange={() => setNotice('Tariff updated for future estimates.')} /><span>/ kWh</span></div></div><div className="setting-row"><div><strong>Refresh interval</strong><small>Demo sensor polling cadence</small></div><strong>2 seconds</strong></div></Card><Card><SectionTitle eyebrow="APPEARANCE" title="Theme" /><div className="theme-options"><button className={!dark ? 'selected' : ''} onClick={() => setDark(false)}><Sun />Light mode</button><button className={dark ? 'selected' : ''} onClick={() => setDark(true)}><Moon />Dark mode</button></div></Card><Card><SectionTitle eyebrow="NOTIFICATIONS" title="Automation" /><div className="toggle-list"><label><span>Abnormal usage alerts</span><input type="checkbox" defaultChecked /></label><label><span>Energy recommendations</span><input type="checkbox" defaultChecked /></label></div></Card></div></> }
